services:
  - type: web
    name: client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: VITE_API_URL
        value: "http://localhost:4000"

  - type: web
    name: api
    env: node
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: MONGO_URI
        value: "your_mongodb_uri"
      - key: JWT_SECRET
        value: "your_jwt_secret"
      - key: CLIENT_ORIGIN
        value: "http://localhost:5174"
      - key: API_PORT
        value: "4000"
